[package]
name = "a_happy_life"
version = "0.1.5"
edition = "2021"

[dependencies]
tempfile = "3.8.1"
uuid = { version = "1.6.1", features = ["v4"] }

[profile.dev]
debug = true
panic = "unwind"

[profile.release]
opt-level = 3
debug = false
lto = true
panic = "unwind"

