[package]
name = "a_happy_life"
version = "0.1.1"
edition = "2021"

[dependencies]
tempfile = "3.8.1"

[profile.dev]
debug = true
panic = "abort"

[profile.release]
opt-level = 3
debug = false
lto = true
panic = "abort"

